### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by LiamHughesWebDev** [trungvose/angular-spotify#95]
When attempting to authorize access for the app to my Spotify account, the page displays:
"Something went wrong, please try again or check out our [help area](https://www.spotify.com/help)"

In the console, it logs:
"Failed to load resource: the server responded with a status of 400 ()"

**Comment by jzelAdmin2006** [comment]
Hi Liam

I was probably able to fix this with my pull request https://github.com/trungvose/angular-spotify/pull/100. You can either wait until Trung accepts it and rolls out the fix, or I don't know if you have a deployment yourself (I was able to run it on the localhost without any problems, for example), in which case you could of course try it yourself.

All the best
JZEL

**Comment by trungvose** [comment]
Should be fixed in #100, thanks @jzelAdmin2006!
